### ISSUE TITLE
How to specify additional certs for ScannerZipInstaller ?

### ISSUE THREAD

**Issue by ring2003** [blackducksoftware/blackduck-common#337]
Hello,

I have problem while scanning which raises an expection in `ScannerZipInstaller.installOrUpdateScanne()` as below, but I cannot find a property I can set to trust for this class.

```java
ERROR [main] --- Could not manage the local keystore - communicating to the server will have to be configured manually: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_144]
at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959) ~[na:1.8.0_144]
at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302) ~[na:1.8.0_144]
at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296) ~[na:1.8.0_144]
at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514) ~[na:1.8.0_144]
at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[na:1.8.0_144]
at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026) ~[na:1.8.0_144]
at sun.security.ssl.Handshaker.process_record(Handshaker.java:961) ~[na:1.8.0_144]
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072) ~[na:1.8.0_144]
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385) ~[na:1.8.0_144]
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413) ~[na:1.8.0_144]
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397) ~[na:1.8.0_144]
at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[na:1.8.0_144]
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[na:1.8.0_144]
at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153) ~[na:1.8.0_144]
at com.synopsys.integration.blackduck.keystore.KeyStoreHelper.updateKeyStoreWithServerCertificate(KeyStoreHelper.java:58) ~[blackduck-common-50.2.0.jar!/:na]
at com.synopsys.integration.blackduck.codelocation.signaturescanner.command.ScannerZipInstaller.downloadIfModified(ScannerZipInstaller.java:168) [blackduck-common-50.2.0.jar!/:na]
at com.synopsys.integration.blackduck.codelocation.signaturescanner.command.ScannerZipInstaller.installOrUpdateScanner(ScannerZipInstaller.java:101) [blackduck-common-50.2.0.jar!/:na]
at com.synopsys.integration.blackduck.codelocation.signaturescanner.ScanBatchRunner.executeScans(ScanBatchRunner.java:98) [blackduck-common-50.2.0.jar!/:na]
at com.synopsys.integration.detect.tool.signaturescanner.BlackDuckSignatureScanner.performScanActions(BlackDuckSignatureScanner.java:97) [classes!/:na]
at com.synopsys.integration.detect.tool.signaturescanner.BlackDuckSignatureScannerTool.runScanTool(BlackDuckSignatureScannerTool.java:121) [classes!/:na]
at com.synopsys.integration.detect.lifecycle.run.RunManager.runBlackDuckProduct(RunManager.java:366) [classes!/:na]
at com.synopsys.integration.detect.lifecycle.run.RunManager.run(RunManager.java:167) [classes!/:na]
at com.synopsys.integration.detect.Application.runApplication(Application.java:168) [classes!/:na]
at com.synopsys.integration.detect.Application.run(Application.java:129) [classes!/:na]
at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:775) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:765) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
at com.synopsys.integration.detect.Application.main(Application.java:91) [classes!/:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [synopsys-detect-6.8.0.jar:na]
at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [synopsys-detect-6.8.0.jar:na]
at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [synopsys-detect-6.8.0.jar:na]
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [synopsys-detect-6.8.0.jar:na]
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397) ~[na:1.8.0_144]
at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302) ~[na:1.8.0_144]
at sun.security.validator.Validator.validate(Validator.java:260) ~[na:1.8.0_144]
at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[na:1.8.0_144]
at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[na:1.8.0_144]
at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[na:1.8.0_144]
at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496) ~[na:1.8.0_144]
... 33 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[na:1.8.0_144]
at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[na:1.8.0_144]
at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) ~[na:1.8.0_144]
at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392) ~[na:1.8.0_144]
... 39 common frames omitted
```

Thanks!

**Comment by ring2003** [comment]
Found it is because running scan in a container, the cacerts is readonly which will raise an exception in https://github.com/blackducksoftware/blackduck-common/blob/d155fc97791f9cd634e02c3edb6f612352c2db1a/src/main/java/com/synopsys/integration/blackduck/keystore/KeyStoreHelper.java#L59 .
